MONGO_URL = 'localhost' 
MONGO_PORT = 27027
MONGO_USER = 'root'
MONGO_PASS = 'password'

RSVPS_TOPIC_NAME= 'meetup-rsvps'


KAFKA_BOOTSTRAP_SERVERS = ['localhost:9092']
KAFKA_CONSUMER_TIMEOUT_MS = 10000
KAFKA_CONSUMER_ENABLE_AUTO_COMMIT = False
KAFKA_CONSUMER_AUTO_OFFSET_RESET = 'earliest'